language: python

install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
