language: python
services:
- docker
python:
- "3.6"
install:
- make deps
script:
- make test
- make lint
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: stark-basin-35443
  api_key: ${HEROKU_API_KEY}
