language: python
services:
- docker
python:
- "3.6"
install:
- make deps
- pip install .
- pip install pytest-cov==4.6.0
- pip install python-coveralls
- pip install -r test_requirements.txt
script:
- make test
- make lint
- make test_cov
- make test_xunit
- make docker_build
- make docker_push
deploy:
  provider: heroku
  app: stark-basin-35443
  api_key: ${HEROKU_API_KEY}
